--------------------------------------------------------
--  File created - Thursday-April-25-2019   
--------------------------------------------------------
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_GENERIC_ARCHIVE.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_GENERIC_RENAME.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_070U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_100U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_102U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_104U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_106U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_108U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_110U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_112U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_114U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_115U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_116U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_117U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_118U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_120U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_124U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_126U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_127U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_128U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_130U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_132U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_134U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_140U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_143U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_200U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_201U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_202U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_204U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_206U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_208U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_210U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_212U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_214U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_220U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_222U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_223U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_224U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_226U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_228U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_300U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_302U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_304U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_306U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_308U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_310U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_312U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_314U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_316U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_318U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_320U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_321U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_322U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_323U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_326U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_328U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_340U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_344U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_345U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_346U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_347U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_348U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_400U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_402U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_404U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_406U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_408U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_410U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_412U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_414U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_416U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_418U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_420U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_422U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_FND_HR_424U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_HR_FOUNDATION\Procedures\WH_WBL_TEST.sql
