--------------------------------------------------------
--  File created - Tuesday-April-16-2019   
--------------------------------------------------------
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\ADW_EXTR_LS_SALES.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\BV_FOODEXTR_CBI.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_014U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_016U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_018TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_018U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_020TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_020U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_020U_BCK10MAR2016.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_021TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_021U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_022TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_022U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_023U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_024TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_024U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_025TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_025U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_026U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_028U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_030U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_032U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_034U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_036U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_040U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_042U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_044U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_046U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_048U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_050U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_052U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_054U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_056U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_058U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_064U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_066FIX.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_066U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_068U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_072U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_074U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_076U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_100U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_100U_OLD.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_102U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_102U_OLD.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_104FIX.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_104FIXF.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_104U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_104U_OLD.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_106U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_108LOD.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_108U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_108U1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_108U1_OLD.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_108U2.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_108U_NEW.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_110FIX.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_110TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_110U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_112U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_112U_1705.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_113U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_120PCI.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_120U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_120U_201805.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_122U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_124U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_134E.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_134E1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_134TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_135U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_140U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_146U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_152TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_152U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_153TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_153U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_154TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_154U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_156U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_157BU.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_157U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_159U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_162U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_165U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_167U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_167U_OLD.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_178TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_178U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_180TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_180U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_180U1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_200U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_202U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_204U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_206FIX.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_206TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_206U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_206U_FIX.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_206U_OLD.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_210U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_212U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_220U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_221U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_222U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_223U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_225U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_230U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_231U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_232U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_233U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_235U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_240U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_241U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_242U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_243U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_245U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_250U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_251U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_252U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_253U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_255U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_260TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_260U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_262FIX.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_262R.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_262TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_262U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_264BUG.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_264FIX.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_264R.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_264TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_264U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_266FIX.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_266TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_266TO1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_266U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_267FIX.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_267TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_267TO1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_267U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_270BU.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_270R.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_270U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_271U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_272R.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_272U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_274U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_276U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_278R.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_278U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_278US.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_280U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_281T.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_281U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_281U1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_282T.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_282U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_282U1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_283U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_284HST.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_284U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_284U1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_287HST.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_287U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_287U1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_290BU.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_290U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_290U_HST1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_290U_HST2.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_290U_RR.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_290U_THEO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_290U_TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_291U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_291U_HST1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_291U_HST2.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_291U_THEO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_291U_TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_292U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_292U_HST1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_292U_HST2.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_292U_THEO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_292U_TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_293U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_293U_HST1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_293U_HST2.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_293U_THEO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_293U_TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_294U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_294U_HST1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_294U_HST2.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_294U_THEO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_294U_TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_300BU.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_300TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_300U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_302U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_310FIX.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_310FX.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_310TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_310U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_315U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_317U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_318TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_318U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_320U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_320U_1803.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_320U_FIX.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_322TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_322U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_324H.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_324SOPH.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_324U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_325H.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_325U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_326H.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_326U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_327H.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_327U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_328H.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_328U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_329H.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_329U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_330H.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_330U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_332H.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_332U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_333H.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_333U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_334H.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_334U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_335H.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_335U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_336H.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_336U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_338H1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_338H2.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_338HQ1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_338U1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_338U2.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_339H1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_339H2.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_339HQ1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_339U1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_339U2.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_340H1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_340H2.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_340HQ1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_340U1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_340U2.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_341H1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_341H2.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_341HQ1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_341U1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_341U2.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_342H1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_342H1FX.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_342H2.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_342HQ1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_342U1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_342U2.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_342U2_FIX.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_343H1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_343H2.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_343HQ1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_343U1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_343U2.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_344H1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_344H2.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_344HQ1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_344U1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_344U2.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_345H1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_345H1N.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_345H2.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_345H2N.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_345HQ1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_345U1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_345U2.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_346U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_347U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_347U_NEW.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_348R.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_348RTO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_348R_FIX.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_348TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_348U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_348U_1803.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_348U_FIX.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_349U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_350U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_351U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_351U_NEW.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_354E.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_358E.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_358E_T.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_362E.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_362E_T.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_364E.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_365E.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_370E.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_370E_29JUN16.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_370E_OLD.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_371E.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_372E.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_373E.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_374E.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_375E.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_376E.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_377E.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_378E.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_379E.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_380E.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_381E.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_382E.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_383E.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_384E.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_400ADW.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_400BU.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_400FIX.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_400U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_400UB.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_400U_HIST.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_400U_NEW.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_446TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_446U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_500U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_502U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_504U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_506U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_508U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_510U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_514U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_516U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_518U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_520U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_530FIX.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_530TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_530U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_530U_BCK16102015.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_530U_ERR.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_530U_ND.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_530U_WL.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_540U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_602FIX.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_602U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_603U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_603U_TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_604U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_610U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_615U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_615U_NEW.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_999T.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_999U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_999UX.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_AUX.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_AUX_FIX.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_AUX_OL.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_BSKT.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_BSKT_FIX.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_BSKT_OL.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_DB1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_DB2.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_DB3.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_DB5.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_DB8.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_DB_TRIAL1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_ITEM.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_ITEM_FIX.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_ITEM_OL.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_ITEM_WK.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_ITEM_WK1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_TNDR.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_TNDR_FIX.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_CUST_TNDR_OL.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_NRT_001U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_NRT_002OLD.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_PRF_NRT_002U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WW_DO_TRUNC.sql
