-- ****** Object: Procedure W7131037.PRC_UPDATE_ITEM_NO Script Date: 13/03/2019 04:41:17 PM ******
CREATE OR REPLACE PROCEDURE "W7131037"."PRC_UPDATE_ITEM_NO" 
(
  P_ITEM_NO IN NUMBER
, P_PRODUCT_FAMILY_CODE IN VARCHAR2
,
  P_vetted CHAR
)

AS
BEGIN

IF UPDATING AND (p_vetted = 'Y')
THEN

UPDATE CUST_LSS_PFC_FEEDBACK
SET PRODUCT_FAMILY_CODE = P_PRODUCT_FAMILY_CODE
WHERE ITEM_NO = P_ITEM_NO;


ELSIF UPDATING AND (p_vetted ='Y')
THEN
   INSERT INTO W7131037.CUST_LSS_PFC_FEEDBACK (ITEM_NO,PRODUCT_FAMILY_CODE)
   VALUES
   (
   P_ITEM_NO,
   P_PRODUCT_FAMILY_CODE
   );

END IF;

END "PRC_UPDATE_ITEM_NO";
