--------------------------------------------------------
--  File created - Tuesday-April-16-2019   
--------------------------------------------------------
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\ADW_DEL_DUP.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WENDY_TEST.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_BULK_LOAD_TEMPLATE.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_005T.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_005U_1.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_010AGE.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_010AGEM.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_010U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_014B.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_014OLD.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_014U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_015U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_018U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_020U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_020U_BCK10MAR2016.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_020U_OLD.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_021HSP.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_021U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_021U_OLD.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_022HSP.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_022U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_022U_OLD.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_023U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_024TEST.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_024U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_024U_OLD.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_024X.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_025PRF.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_025U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_026U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_027U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_028U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_029U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_030U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_032U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_034U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_036U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_040U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_042U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_044U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_046U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_048U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_050U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_052U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_054U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_056U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_058U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_060U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_061U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_062U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_064U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_066U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_068U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_072U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_074U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_076U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_086U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_100U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_100U_OLD.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_102U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_102U_OLD.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_104U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_104U_OLD.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_106U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_110U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_112U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_114U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_116U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_120U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_120U_201805.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_122U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_124U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_126U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_127U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_130U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_130U_TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_132U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_132U_TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_140U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_146U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_152U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_153U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_154U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_156U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_160U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_162U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_165U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_167U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_290U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_291U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_292U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_293U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_294U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_500U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_502U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_504U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_506U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_508U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_510U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_514U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_516U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_518U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_520U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_530U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_530U_BCK16102015.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_530U_TEST.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_530U_TSTWL.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_530U_WL.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_600U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_602M.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_602U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_610ID.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_610U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_615U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_615U_201811.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_620FIX.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_620ID.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_620U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_ARCHIVE_CLEAN.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_EXT_BU_MTH.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_CUST_EXT_GRP_MTH.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_GENERIC_ARCHIVE.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_GENERIC_RENAME.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_GENERIC_RENAME_Q.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_NRT_010U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_STG_LOAD.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_WFS_020U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_WFS_022U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_WFS_024U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_WFS_026U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WH_FND_WFS_028U.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\WW_DO_TRUNC.sql
@C:\TFS\DWH-Sandbox\VC_Master\Procedures\adw_del_dup_1.sql
