--------------------------------------------------------
--  File created - Thursday-April-25-2019   
--------------------------------------------------------
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_GENERIC_ARCHIVE.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_GENERIC_RENAME.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_012U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_016U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_020U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_022U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_024U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_026U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_028U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_030U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_032U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_034U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_036U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_038U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_040U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_042U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_044U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_046U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_052U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_054U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_056U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_058U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_060U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_062U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_064U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_066U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_068U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_070U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_072U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_074U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_076U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_078U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_080U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_084U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_086U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_088U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_090U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_092U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_094U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_096U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_098U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_100U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_102U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_104U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_106U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_108U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_110U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_112U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_114U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_116U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_118U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_120U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_122U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_124U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_126U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_128U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_130U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_132U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_134U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_136U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_138U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_140U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_150U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_150U_20181117.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_152U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_154U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_156HSP.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_156U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_156U_20190409.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_157U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_158U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_159U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_160U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_162HSP.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_162U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_162U_20161027.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_162U_20170601.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_164TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_164U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_166TO.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_166U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_168U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_168U_20181117.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_170U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_170U_20170601.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_172U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_178U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_184U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_200U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_204HSP.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_204U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_205M.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_205OLD.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_205U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_206U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_208BU.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_208MB.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_208U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_208U_NEW.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_210U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_216U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_218U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_220U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_222U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_224U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_226U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_228U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_230U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_230U_BKJUN.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_232U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_300U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_302U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_304U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_306U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_308U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_310U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_312U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_314U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_316FIX.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_316OLD.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_316T.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_316U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_316U_FIXNC.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_318HSP.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_318OLD.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_318U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_320U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_322U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_324U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_326OLD.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_326U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_328U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_330U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_400U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_402U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_410U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_411U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_411U_20161027.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_412U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_413U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_414U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_414U_20181117.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_415U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_416U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_417U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_418U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_419U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_420U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_421U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_422U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_424U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_450U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_460U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_462U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_464U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_468U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_468U_20180905.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_470U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_472U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_474U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_476U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_478U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_480U.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_ARCHIVE_CLEAN.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WH_FND_WFS_VTKO.sql
@C:\TFS\DWH-Sandbox\VC_Master\DWH_WFS_FOUNDATION\Procedures\WW_DO_TRUNC.sql
