--------------------------------------------------------
--  DDL for Procedure AAWL_2RUN
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "DWH_PERFORMANCE"."AAWL_2RUN" (p_forall_limit in integer, p_success out boolean) as

--**************************************************************************************************
--  Date:        August 2013
--  Author:      Wendy lyttle
--  Purpose:     Tests stats

--**************************************************************************************************
g_recs_read          integer       :=  0;
g_recs_updated       integer       :=  0;
g_recs_inserted      integer       :=  0;
g_recs_hospital      integer       :=  0;
g_forall_limit       integer       :=  dwh_constants.vc_forall_limit;
g_error_count        number        :=  0;
g_error_index        number        :=  0;
g_rec_out            dwh_performance.rtl_loc_item_wk_sales_index%rowtype;
g_count              number        :=  0;
g_found              boolean;
g_SQL              VARCHAR2(4000);
g_date               date          := trunc(sysdate);
g_yesterday          date          := trunc(sysdate) - 1;


l_message            sys_dwh_errlog.log_text%type;
l_module_name        sys_dwh_errlog.log_procedure_name%type    := 'AAWL_2RUN';
l_name               sys_dwh_log.log_name%type                 := dwh_constants.vc_log_name_rtl_md;
l_system_name        sys_dwh_log.log_system_name%type          := dwh_constants.vc_log_system_name_rtl_prf;
l_script_name        sys_dwh_log.log_script_name%type          := dwh_constants.vc_log_script_rtl_prf_md;
l_procedure_name     sys_dwh_log.log_procedure_name%type       := l_module_name;
l_text               sys_dwh_log.log_text%type ;
l_description        sys_dwh_log_summary.log_description%type  := 'test stats';
l_process_type       sys_dwh_log_summary.log_process_type%type := dwh_constants.vc_log_process_type_n;

-- For output arrays into bulk load forall statements --
type tbl_array_i is table of dwh_performance.rtl_loc_item_wk_sales_index%rowtype index by binary_integer;
type tbl_array_u is table of dwh_performance.rtl_loc_item_wk_sales_index%rowtype index by binary_integer;
a_tbl_insert        tbl_array_i;
a_tbl_update        tbl_array_u;
a_empty_set_i       tbl_array_i;
a_empty_set_u       tbl_array_u;
a_count             integer       := 0;
a_count_i           integer       := 0;
a_count_u           integer       := 0;
l_from_date         date := trunc(sysdate) - 1;
l_fin_year_no       number;
l_fin_week_no       number;
l_fin_year_month_no       number;
l_last_wk_start_date date;
l_last_wk_end_date    date;
l_last_wk_ly_start_date date;
l_last_wk_ly_end_date   date;

g_start_date date;

g_partition_name varchar2(40);

l_ly_fin_year_no    number;
l_ly_fin_week_no    number;

--**************************************************************************************************
-- Main process loop
--**************************************************************************************************
begin

    if p_forall_limit is not null and p_forall_limit > dwh_constants.vc_forall_minimum then
       g_forall_limit := p_forall_limit;
    end if;
    dbms_output.put_line('Bulk write limit '||p_forall_limit||' '||g_forall_limit);
    p_success := false;

    l_text := dwh_constants.vc_log_draw_line;
    dwh_log.write_log(l_name,l_system_name,l_script_name,l_procedure_name,l_text);

    l_text := 'started AT '||
    to_char(sysdate,('dd mon yyyy hh24:mi:ss'));
    dwh_log.write_log(l_name,l_system_name,l_script_name,l_procedure_name,l_text);

    dwh_log.insert_log_summary(l_name,l_system_name,l_script_name,l_procedure_name,l_description,
    l_process_type,dwh_constants.vc_log_started,'','','','','');

-- ######################################################################################### --
-- The outer joins are needed as there are cases when there are no sales in dense for items  --
-- which must be included in order to show a zero sales index as these records will be       --
-- created when the outer joins to either dense LY or the item price records are found       --
-- ######################################################################################### --

EXECUTE IMMEDIATE ('

  CREATE TABLE DWH_PERFORMANCE.MART_CHASTCHNGRDSCWK_SEASON 
   (	SK1_CHAIN_NO NUMBER(9,0) NOT NULL ENABLE, 
	SK1_GRADE_NO NUMBER(9,0) NOT NULL ENABLE, 
	SK1_STYLE_COLOUR_NO NUMBER(9,0) NOT NULL ENABLE, 
	FIN_YEAR_NO NUMBER(4,0) NOT NULL ENABLE, 
	FIN_WEEK_NO NUMBER(2,0) NOT NULL ENABLE, 
	FIN_WEEK_CODE VARCHAR2(7 BYTE) NOT NULL ENABLE, 
	REG_RSP_INCL_VAT NUMBER(14,2), 
	SALES_ACT NUMBER(14,2), 
	COST_PRICE_ACT NUMBER(14,2), 
	SELLING_RSP_ACT NUMBER(14,2), 
	CHAIN_INTAKE_MARGIN_ACT NUMBER(14,2), 
	SALES_QTY_ACT NUMBER(14,3), 
	SALES_PLANNED_QTY_PRE_ACT NUMBER(14,3), 
	TARGET_STOCK_QTY_ACT NUMBER(14,3), 
	APS_SALES_QTY_ACT NUMBER(14,3), 
	SALES_STD_ACT NUMBER(14,2), 
	SALES_MARGIN_STD_ACT NUMBER(14,2), 
	STORE_INTAKE_SELLING_STD_ACT NUMBER(14,2), 
	SALES_QTY_STD_ACT NUMBER(14,3), 
	TARGET_STOCK_QTY_STD_ACT NUMBER(14,3), 
	SALES_QTY_6WK_ACT NUMBER(14,3), 
	SALES_6WK_ACT NUMBER(14,2), 
	TARGET_STOCK_SELLING_6WK_ACT NUMBER(14,2), 
	STORE_COUNT_ACT NUMBER(4,0), 
	PROM_SALES_QTY_ACT NUMBER(14,3), 
	PROM_SALES_SELLING_ACT NUMBER(14,2), 
	CLEAR_SALES_QTY_ACT NUMBER(14,3), 
	CLEAR_SALES_SELLING_ACT NUMBER(14,2), 
	TARGET_STOCK_SELLING_ACT NUMBER(14,2), 
	REG_SALES_QTY_ACT NUMBER(14,3), 
	REG_SALES_SELLING_ACT NUMBER(14,2), 
	LAST_UPDATED_DATE DATE NOT NULL ENABLE, 
	NUM_AVAIL_DAYS_6WK_ACT NUMBER(6,0), 
	NUM_CATLG_DAYS_6WK_ACT NUMBER(6,0), 
	CHAIN_INTAKE_SELLING_ACT NUMBER(14,2), 
	CHAIN_INTAKE_SELLING_STD_ACT NUMBER(14,2), 
	CHAIN_INTAKE_MARGIN_STD_ACT NUMBER(14,2)
   )  LOGGING
  TABLESPACE PRF_MASTER 
');
COMMIT;

  EXECUTE IMMEDIATE ('ALTER TABLE DWH_PERFORMANCE.MART_CHASTCHNGRDSCWK_SEASON ADD CONSTRAINT PK_MART_CHASTCHNGRDSCWK_SEASON PRIMARY KEY (SK1_CHAIN_NO, SK1_GRADE_NO, SK1_STYLE_COLOUR_NO, FIN_YEAR_NO, FIN_WEEK_NO)
  USING INDEX 
  TABLESPACE PRF_MASTER  ENABLE');
  commit;


  EXECUTE IMMEDIATE ('CREATE INDEX DWH_PERFORMANCE.I10_MART_CHASTCHNGRDSCWK_SSN ON DWH_PERFORMANCE.MART_CHASTCHNGRDSCWK_SEASON (LAST_UPDATED_DATE) 
    TABLESPACE PRF_MASTER');
    
  EXECUTE IMMEDIATE ('CREATE OR REPLACE PUBLIC SYNONYM MART_CHASTCHNGRDSCWK_SEASON FOR DWH_PERFORMANCE.MART_CHASTCHNGRDSCWK_SEASON');
COMMIT;

    EXECUTE IMMEDIATE ('GRANT SELECT ON DWH_PERFORMANCE.MART_CHASTCHNGRDSCWK_SEASON TO READ_ONLY');
    EXECUTE IMMEDIATE ('GRANT DELETE ON DWH_PERFORMANCE.MART_CHASTCHNGRDSCWK_SEASON TO DATA_FIX_ROLE');
    EXECUTE IMMEDIATE ('GRANT INSERT ON DWH_PERFORMANCE.MART_CHASTCHNGRDSCWK_SEASON TO DATA_FIX_ROLE');
    EXECUTE IMMEDIATE ('GRANT SELECT ON DWH_PERFORMANCE.MART_CHASTCHNGRDSCWK_SEASON TO DATA_FIX_ROLE');
    EXECUTE IMMEDIATE ('GRANT UPDATE ON DWH_PERFORMANCE.MART_CHASTCHNGRDSCWK_SEASON TO DATA_FIX_ROLE');
    
/*EXECUTE IMMEDIATE ('
CREATE INDEX DWH_PERFORMANCE.i2_tmp_po_spchn_dtfx ON dwh_datafix.temp_po_supchain_datafix (SK1_LOCATION_NO
,SK1_ITEM_NO
,SK1_PO_NO) 
LOGGING 
TABLESPACE PRF_MASTER');
COMMIT;
*/
/*
insert into dwh_datafix.qc4906_desc
select item_no, department_no, class_no, subclass_no, item_short_desc, desccc, descc from 
(SELECT item_no, department_no, class_no, subclass_no, item_short_desc, desc1, desc2, desc3, desc4, desc5,
desc1||desc2 desc12, 
desc2||desc3 desc23, 
desc3||desc4 desc34, 
desc4||desc5 desc45
FROM   dwh_datafix.qc4906_ext
--where item_no    IN (9002490100070,9002490200220)
--          AND location_no   = 1013
          )
UNPIVOT (descc FOR desccc IN 
(desc1 AS '1', 
desc2 AS '2', 
desc3 AS '3', 
desc4 AS '4',
desc5 AS '5', 
desc12 AS '12', 
desc23 AS '23', 
desc34 AS '34',
desc45 AS '45'
))
group by item_no, department_no, class_no, subclass_no, item_short_desc, desccc, descc
;
commit;

/*
g_start_date := '22 sep 2013';
FOR g_sub IN 0..6
LOOP

  g_start_date := g_start_date + 1;
  
  l_text       := 'ROLLUP RANGE IS:- '||g_start_date;
  dwh_log.write_log(l_name,l_system_name,l_script_name,l_procedure_name,l_text); 
  
  UPDATE rtl_loc_item_dy_rdf_fcst
  SET STATIC_WK_DLY_APP_FCST_QTY            = SALES_DLY_APP_FCST_QTY
  WHERE post_date =  g_start_date
  and (STATIC_WK_DLY_APP_FCST_QTY   is null
  or STATIC_WK_DLY_APP_FCST_QTY = 0);
  
  g_recs_read := g_recs_read    + SQL%ROWCOUNT;
  
  g_recs_updated                           := g_recs_updated + SQL%ROWCOUNT;
  
  l_text                                   := 'recs updated = '||g_recs_read;
  dwh_log.write_log(l_name,l_system_name,l_script_name,l_procedure_name,l_text);
  
  COMMIT;
  
END LOOP;
*/

/*
  EXECUTE IMMEDIATE ('CREATE TABLE DWH_PERFORMANCE.RTL_AST_SC_BURST 
   (	TRAN_DATE DATE NOT NULL ENABLE, 
	SK1_SUBCLASS_NO NUMBER(9,0), 
	LAST_UPDATED_DATE DATE NOT NULL ENABLE
   ) 
  TABLESPACE PRF_MASTER ');
COMMIT;
  
    EXECUTE IMMEDIATE ('ALTER TABLE DWH_PERFORMANCE.RTL_AST_SC_BURST ADD CONSTRAINT PK_P_RTL_AST_SC_BRST PRIMARY KEY (TRAN_DATE, SK1_SUBCLASS_NO)
  USING INDEX 
  TABLESPACE PRF_MASTER  ENABLE');
COMMIT;
  
    EXECUTE IMMEDIATE ('GRANT SELECT ON DWH_PERFORMANCE.RTL_AST_SC_BURST TO READ_ONLY');
COMMIT;
    EXECUTE IMMEDIATE ('GRANT DELETE ON DWH_PERFORMANCE.RTL_AST_SC_BURST TO DATA_FIX_ROLE');
COMMIT;
    EXECUTE IMMEDIATE ('GRANT INSERT ON DWH_PERFORMANCE.RTL_AST_SC_BURST TO DATA_FIX_ROLE');
COMMIT;
    EXECUTE IMMEDIATE ('GRANT SELECT ON DWH_PERFORMANCE.RTL_AST_SC_BURST TO DATA_FIX_ROLE');
COMMIT;
    EXECUTE IMMEDIATE ('GRANT UPDATE ON DWH_PERFORMANCE.RTL_AST_SC_BURST TO DATA_FIX_ROLE');
COMMIT;
*/

/*
  EXECUTE IMMEDIATE ('CREATE OR REPLACE PUBLIC SYNONYM RTL_AST_SC_BURST FOR DWH_PERFORMANCE.RTL_AST_SC_BURST');
COMMIT;

Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),3932,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),3933,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),3942,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),3955,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),3957,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),3982,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),3985,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),3987,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5136,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5147,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5148,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5170,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5171,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5186,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5187,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5205,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5212,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5213,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5221,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5222,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5246,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5251,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5252,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5261,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5262,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5263,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5264,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5265,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5266,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5267,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5268,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5269,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5270,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5398,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5400,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5401,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5404,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5407,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5411,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5412,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5422,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5423,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5425,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5427,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5433,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5435,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6973,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6975,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6993,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7000,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7007,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7156,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7327,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7328,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7329,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7330,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7331,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7332,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7433,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7483,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7488,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7490,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7492,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7493,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7494,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7499,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7578,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7579,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7580,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7581,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7582,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7583,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7584,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7613,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7614,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7638,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7639,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7640,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7653,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7654,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7655,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7656,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7657,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7658,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7755,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7756,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7757,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7758,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7759,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7760,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7761,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6211713,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6211715,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6219407,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6219409,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6219427,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6219428,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6219430,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6219458,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6219459,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6219460,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6219461,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6219462,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6219463,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6219464,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6219465,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14133809,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14133811,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14133813,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14207510,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14207511,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14207512,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14207516,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14207517,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14212320,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14212321,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14212322,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14212323,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14212324,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14212325,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14212326,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14212327,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14212328,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14212329,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14212330,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14212331,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14212332,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14212333,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14212334,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14212335,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14212336,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14212338,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5438,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5444,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5446,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5450,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5452,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5453,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5454,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5455,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5456,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5458,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5463,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5474,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5475,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5478,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5498,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5499,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5500,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5501,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5511,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5514,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5515,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5524,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5525,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5532,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5537,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),1480091,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),1480092,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),1480093,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),1480094,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),1497580,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5488154,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5488155,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5488156,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5488157,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5488158,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5488159,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5496188,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5496189,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5537149,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5597050,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5597051,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5597052,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5669925,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5669926,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5720149,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5720150,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5720151,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5720152,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14255128,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14255129,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14255130,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14255131,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14255132,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14255134,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14255136,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14255137,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14255138,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14262216,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14262217,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14383786,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14383787,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14383788,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14383789,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14383790,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14383791,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14388945,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14388946,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14388947,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14388948,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14388949,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14388950,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14388951,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14388952,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14388953,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14388954,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14722270,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),14722271,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4564,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4566,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4567,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4568,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4569,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4571,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4609,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4610,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4618,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4619,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4620,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4625,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4626,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4634,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4637,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4660,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4661,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4662,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4704,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4707,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4708,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4711,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4712,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4725,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4733,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4735,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4736,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4743,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4744,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4757,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4784,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4789,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4790,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4791,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4792,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4797,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4801,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4802,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4817,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4818,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4819,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4820,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4844,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4851,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4854,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4864,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4924,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4925,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4941,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4949,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4959,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4960,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4963,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4964,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4995,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),4996,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5013,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5027,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5030,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),5056,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6346,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6371,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7889,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7892,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7893,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7894,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7895,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7921,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7922,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7923,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7924,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7925,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7926,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7927,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7929,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7930,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7931,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7932,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7934,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7970,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7982,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),7987,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),8014,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),8015,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),8016,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),8017,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),8018,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),8019,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),8020,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),8021,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),8022,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),8023,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),17284452,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),18189372,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),18189373,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),18481457,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),15253889,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),15253890,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),15253891,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),15318261,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),15511665,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),15822329,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16112383,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16112384,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16112385,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16112386,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16124775,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16124776,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16334473,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16334474,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16334475,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16334476,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16334477,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16334478,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16334479,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16334480,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16334481,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16334482,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16334483,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16334484,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16334485,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16334488,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16334490,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16334588,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16334589,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16334590,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16334591,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16334592,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16334613,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16347304,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16347305,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16347308,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16347309,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16347310,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16347311,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16347312,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16347313,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16347314,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16347315,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16347316,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16347317,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16347318,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16347319,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16347320,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16347321,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),16454665,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),8228,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),8229,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),8230,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),8306,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),8310,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),8311,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),8377,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),8378,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),8379,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),8381,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),8382,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),8383,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),8384,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),8385,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),8386,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),8387,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),8388,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),8389,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),8390,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),8391,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),8392,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),8393,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),8394,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),8395,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),8396,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6458,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6459,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6460,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6461,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6462,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6463,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6464,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6465,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6466,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6467,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6468,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6469,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6470,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6471,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6472,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6473,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6474,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6475,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6476,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6477,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6478,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6479,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6480,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6481,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6482,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6483,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6484,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6485,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6486,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6487,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6488,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6489,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6490,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6491,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6492,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6493,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6494,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6495,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6496,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6497,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6498,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6499,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6501,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6510,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6511,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6512,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6513,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6520,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6521,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6522,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6523,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6534,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6535,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6536,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6537,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6538,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6539,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6540,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6541,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6542,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6543,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6826,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6827,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6828,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6829,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6830,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6831,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6832,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6841,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6891,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6892,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6893,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6918,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6934,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6938,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6950,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6952,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6963,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),6964,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19217131,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19220587,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19220588,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19220589,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19220590,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19220591,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19223840,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19223841,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19223842,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19223844,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19223851,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19223852,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19223853,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19223893,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19223894,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19238432,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19238433,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19238434,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19238435,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19238436,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19238437,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19238438,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19243299,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19243300,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19243301,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19243302,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19243303,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19243304,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19243305,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19243351,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19288608,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19288614,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19288615,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19288616,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19288617,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19288618,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19288619,to_date('26/NOV/13','DD/MON/RR'));
Insert into DWH_PERFORMANCE.RTL_AST_SC_BURST (TRAN_DATE,SK1_SUBCLASS_NO,LAST_UPDATED_DATE) values (to_date('26/NOV/13','DD/MON/RR'),19288620,to_date('26/NOV/13','DD/MON/RR'));
COMMIT;
/*SELECT '26/NOV/2013', SK1_SUBCLASS_NO, '26/NOV/2013' FROM DIM_SUBCLASS
WHERE SUBCLASS_NO IN (5161
,5162
,5277
,5278
,5279
,5280
,5282
,5283
,5284
,5286
,5287
,5289
,5290
,5291
,5292
,5338
,5339
,5340
,5341
,5343)*/
--**************************************************************************************************
-- Write final log data
--**************************************************************************************************

    dwh_log.update_log_summary(l_name,l_system_name,l_script_name,l_procedure_name,l_description,
    l_process_type,dwh_constants.vc_log_ended,g_recs_read,g_recs_inserted,g_recs_updated,'',g_recs_hospital);

    l_text :=  dwh_constants.vc_log_time_completed||to_char(sysdate,('dd mon yyyy hh24:mi:ss'));
    dwh_log.write_log(l_name,l_system_name,l_script_name,l_procedure_name,l_text);
    l_text :=  dwh_constants.vc_log_records_read||g_recs_read;
    dwh_log.write_log(l_name,l_system_name,l_script_name,l_procedure_name,l_text);
    l_text :=  dwh_constants.vc_log_records_updated||g_recs_updated;
    dwh_log.write_log(l_name,l_system_name,l_script_name,l_procedure_name,l_text);
    l_text :=  dwh_constants.vc_log_records_inserted||g_recs_inserted;
    dwh_log.write_log(l_name,l_system_name,l_script_name,l_procedure_name,l_text);
    l_text :=  dwh_constants.vc_log_records_hospital||g_recs_hospital;
    dwh_log.write_log(l_name,l_system_name,l_script_name,l_procedure_name,l_text);
    l_text := dwh_constants.vc_log_run_completed||sysdate;
    dwh_log.write_log(l_name,l_system_name,l_script_name,l_procedure_name,l_text);
    l_text := dwh_constants.vc_log_draw_line;
    dwh_log.write_log(l_name,l_system_name,l_script_name,l_procedure_name,l_text);
        l_text :=  ' ';
    dwh_log.write_log(l_name,l_system_name,l_script_name,l_procedure_name,l_text);
    commit;
    p_success := true;
   exception
      when dwh_errors.e_insert_error then
       l_message := dwh_constants.vc_err_mm_insert||sqlcode||' '||sqlerrm;
       dwh_log.record_error(l_module_name,sqlcode,l_message);
       dwh_log.update_log_summary(l_name,l_system_name,l_script_name,l_procedure_name,l_description,
                                  l_process_type,dwh_constants.vc_log_aborted,'','','','','');
       rollback;
       p_success := false;
       raise;

      when others then
       l_message := dwh_constants.vc_err_mm_other||sqlcode||' '||sqlerrm;
       dwh_log.record_error(l_module_name,sqlcode,l_message);
       dwh_log.update_log_summary(l_name,l_system_name,l_script_name,l_procedure_name,l_description,
                                  l_process_type,dwh_constants.vc_log_aborted,'','','','','');
       rollback;
       p_success := false;
       raise;


END AAWL_2RUN;
