--------------------------------------------------------
--  DDL for Procedure RUN_S4S_CLONED_PROCS_SS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "DWH_PERFORMANCE"."RUN_S4S_CLONED_PROCS_SS" 
(p_forall_limit in integer,p_success out boolean) as 

g_forall_limit       integer       :=  10000;

BEGIN

  -- FOUNDATION LAYER 

  DWH_FOUNDATION.WH_FND_S4S_014U_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_FOUNDATION.WH_FND_S4S_014A_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_FOUNDATION.WH_FND_S4S_014B_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_FOUNDATION.WH_FND_S4S_014C_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_FOUNDATION.WH_FND_S4S_014D_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_FOUNDATION.WH_FND_S4S_014E_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS); 

  -- PERFORMANCE LAYER

  DWH_PERFORMANCE.WH_PRF_S4S_014A_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_PERFORMANCE.WH_PRF_S4S_014B_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_PERFORMANCE.WH_PRF_S4S_014C_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_PERFORMANCE.WH_PRF_S4S_014D_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_PERFORMANCE.WH_PRF_S4S_014E_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);

  --HSP
  DWH_FOUNDATION.WH_FND_S4S_005U_SS_HSP(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);  

  DWH_PERFORMANCE.WH_PRF_S4S_006U_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_PERFORMANCE.WH_PRF_S4S_021U_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_PERFORMANCE.WH_PRF_S4S_063U_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_PERFORMANCE.WH_PRF_S4S_065U_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_PERFORMANCE.WH_PRF_S4S_075U_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_PERFORMANCE.WH_PRF_S4S_073U_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_PERFORMANCE.WH_PRF_S4S_022U_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);

  DWH_PERFORMANCE.WH_PRF_S4S_050U_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_PERFORMANCE.WH_PRF_S4S_005U_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_PERFORMANCE.WH_PRF_S4S_009U_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_PERFORMANCE.WH_PRF_S4S_032U_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_PERFORMANCE.WH_PRF_S4S_051U_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);  
  DWH_PERFORMANCE.WH_PRF_S4S_044U_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);   

  DWH_PERFORMANCE.WH_PRF_S4S_004A_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_PERFORMANCE.WH_PRF_S4S_004U_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_PERFORMANCE.WH_PRF_S4S_008U_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);

END RUN_S4S_CLONED_PROCS_SS;
