--------------------------------------------------------
--  DDL for Procedure RUN_S4S_CLONED_PROCS_A_SEED_SS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "DWH_PERFORMANCE"."RUN_S4S_CLONED_PROCS_A_SEED_SS" 
(p_forall_limit in integer,p_success out boolean) as

g_forall_limit       integer       :=  10000;

BEGIN

-- SEED S4S before new daily batch run...

--XX
EXECUTE IMMEDIATE('TRUNCATE TABLE DWH_PERFORMANCE.RTL_LOC_EMP_JOB_PAYCAT_DY_SS');

EXECUTE IMMEDIATE('TRUNCATE TABLE DWH_PERFORMANCE.RTL_LOC_EMP_JOB_PAYCAT_WK_SS');
EXECUTE IMMEDIATE('TRUNCATE TABLE DWH_PERFORMANCE.RTL_LOC_BU_WK_SS');
EXECUTE IMMEDIATE('TRUNCATE TABLE DWH_PERFORMANCE.RTL_LOC_JOB_WK_SS');
EXECUTE IMMEDIATE('TRUNCATE TABLE DWH_PERFORMANCE.RTL_EMP_AVAIL_LOC_JOB_DY_SS');
EXECUTE IMMEDIATE('TRUNCATE TABLE DWH_PERFORMANCE.RTL_EMP_AVAIL_LOC_JOB_WK_SS');
EXECUTE IMMEDIATE('TRUNCATE TABLE DWH_PERFORMANCE.RTL_EMP_CONSTR_LOC_JOB_WK_SS');

--XX
EXECUTE IMMEDIATE('TRUNCATE TABLE DWH_PERFORMANCE.RTL_EMP_JOB_DY_SS');

EXECUTE IMMEDIATE('TRUNCATE TABLE DWH_PERFORMANCE.RTL_EMP_JOB_WK_SS');
EXECUTE IMMEDIATE('TRUNCATE TABLE DWH_PERFORMANCE.RTL_ACTL_XCPTN_EMP_DY_SS');
EXECUTE IMMEDIATE('TRUNCATE TABLE DWH_PERFORMANCE.RTL_ACTL_XCPTN_EMP_WK_SS');
EXECUTE IMMEDIATE('TRUNCATE TABLE DWH_PERFORMANCE.RTL_SCHED_XCPTN_EMP_DY_SS');
EXECUTE IMMEDIATE('TRUNCATE TABLE DWH_PERFORMANCE.RTL_SCHED_XCPTN_EMP_WK_SS');
EXECUTE IMMEDIATE('TRUNCATE TABLE DWH_PERFORMANCE.RTL_SCH_LOC_EMP_JB_DY_SS');
EXECUTE IMMEDIATE('TRUNCATE TABLE DWH_PERFORMANCE.RTL_SCH_LOC_EMP_JB_WK_SS');

INSERT /*+ append */ INTO DWH_PERFORMANCE.RTL_LOC_JOB_WK_SS
SELECT /*+ PARALLEL(a,6) */ 
     *  FROM DWH_PERFORMANCE.RTL_LOC_JOB_WK A 
WHERE FIN_YEAR_NO IN (2018,2019)
AND SK1_JOB_ID IN (SELECT  /*+ PARALLEL(b,6) */ SK1_JOB_ID FROM DWH_PERFORMANCE.RTL_JOB_SS B);
COMMIT;

INSERT /*+ append */ INTO DWH_PERFORMANCE.RTL_LOC_BU_WK_SS
SELECT /*+ PARALLEL(a,6) */ * FROM DWH_PERFORMANCE.RTL_LOC_BU_WK  A
WHERE FIN_YEAR_NO IN (2018,2019)
AND SK1_S4S_BUSINESS_UNIT_NO IN (SELECT  /*+ PARALLEL(b,6) */ SK1_S4S_BUSINESS_UNIT_NO FROM DWH_PERFORMANCE.RTL_S4S_BUSINESS_UNIT_SS B);
COMMIT;


INSERT /*+ append */ INTO DWH_PERFORMANCE.RTL_EMP_CONSTR_LOC_JOB_WK_SS
SELECT /*+ PARALLEL(a,6) */ * FROM DWH_PERFORMANCE.RTL_EMP_CONSTR_LOC_JOB_WK A 
WHERE FIN_YEAR_NO IN (2018,2019)
AND SK1_JOB_ID IN (SELECT  /*+ PARALLEL(b,6) */ SK1_JOB_ID FROM DWH_PERFORMANCE.RTL_JOB_SS B);
COMMIT;

INSERT /*+ append */ INTO DWH_PERFORMANCE.RTL_EMP_AVAIL_LOC_JOB_WK_SS
SELECT /*+ PARALLEL(a,6) */ * FROM DWH_PERFORMANCE.RTL_EMP_AVAIL_LOC_JOB_WK A 
WHERE FIN_YEAR_NO IN (2018,2019)
AND SK1_JOB_ID IN (SELECT  /*+ PARALLEL(b,6) */ SK1_JOB_ID FROM DWH_PERFORMANCE.RTL_JOB_SS B);
COMMIT;

INSERT /*+ append */ INTO DWH_PERFORMANCE.RTL_SCH_LOC_EMP_JB_WK_SS
SELECT /*+ PARALLEL(a,6) */ * FROM DWH_PERFORMANCE.RTL_SCH_LOC_EMP_JB_WK A 
WHERE FIN_YEAR_NO IN (2018,2019)
AND SK1_JOB_ID IN (SELECT  /*+ PARALLEL(b,6) */ SK1_JOB_ID FROM DWH_PERFORMANCE.RTL_JOB_SS B);
COMMIT;

INSERT /*+ append */ INTO DWH_PERFORMANCE.RTL_LOC_EMP_JOB_PAYCAT_WK_SS
SELECT /*+ PARALLEL(a,6) */ * FROM  DWH_PERFORMANCE.RTL_LOC_EMP_JOB_PAYCAT_WK A 
WHERE FIN_YEAR_NO IN (2018,2019)
AND SK1_JOB_ID IN (SELECT  /*+ PARALLEL(b,6) */ SK1_JOB_ID FROM DWH_PERFORMANCE.RTL_JOB_SS B);
COMMIT;

INSERT /*+ append */ INTO DWH_PERFORMANCE.RTL_EMP_AVAIL_LOC_JOB_DY_SS
SELECT  /*+ PARALLEL(a,6) */ * FROM DWH_PERFORMANCE.RTL_EMP_AVAIL_LOC_JOB_DY A
WHERE TRAN_DATE >= '26/JUN/2017'
AND SK1_JOB_ID IN (SELECT  /*+ PARALLEL(b,6) */ SK1_JOB_ID FROM DWH_PERFORMANCE.RTL_JOB_SS B);
COMMIT;

INSERT /*+ append */ INTO   DWH_PERFORMANCE.RTL_SCH_LOC_EMP_JB_DY_SS
SELECT  /*+ PARALLEL(a,6) */ * FROM DWH_PERFORMANCE.RTL_SCH_LOC_EMP_JB_DY A
WHERE SHIFT_CLOCK_IN >= '26/JUN/2017'
AND SK1_JOB_ID IN (SELECT  /*+ PARALLEL(b,6) */ SK1_JOB_ID FROM DWH_PERFORMANCE.RTL_JOB_SS B);
COMMIT;

--005U!!!!
INSERT /*+ append */ INTO   DWH_PERFORMANCE.RTL_EMP_JOB_DY_SS
SELECT  /*+ PARALLEL(a,6) */ * FROM DWH_PERFORMANCE.RTL_EMP_JOB_DY A
WHERE JOB_START_DATE >= '26/JUN/2017'
AND SK1_JOB_ID IN (SELECT  /*+ PARALLEL(b,6) */ SK1_JOB_ID FROM DWH_PERFORMANCE.RTL_JOB_SS B);
COMMIT;

--006U!!!
INSERT /*+ append */ INTO DWH_PERFORMANCE.RTL_LOC_EMP_JOB_PAYCAT_DY_SS
SELECT /*+ PARALLEL(a,6) */ * FROM  DWH_PERFORMANCE.RTL_LOC_EMP_JOB_PAYCAT_DY A 
WHERE BUSINESS_DATE >= '26/JUN/2017'
AND SK1_JOB_ID IN (SELECT  /*+ PARALLEL(b,6) */ SK1_JOB_ID FROM DWH_PERFORMANCE.RTL_JOB_SS B);
COMMIT;

INSERT /*+ append */ INTO DWH_PERFORMANCE.RTL_EMP_JOB_WK_SS
SELECT /*+ PARALLEL(a,6) */ * FROM  DWH_PERFORMANCE.RTL_EMP_JOB_WK A 
WHERE JOB_START_DATE >= '26/JUN/2017'
AND SK1_JOB_ID IN (SELECT  /*+ PARALLEL(b,6) */ SK1_JOB_ID FROM DWH_PERFORMANCE.RTL_JOB_SS B);
COMMIT;

INSERT /*+ append */ INTO DWH_PERFORMANCE.RTL_ACTL_XCPTN_EMP_DY_SS
SELECT /*+ PARALLEL(a,6) */ * FROM  DWH_PERFORMANCE.RTL_ACTL_XCPTN_EMP_DY A 
WHERE EXCEPTION_DATE >= '26/JUN/2017'
AND SK1_JOB_ID IN (SELECT  /*+ PARALLEL(b,6) */ SK1_JOB_ID FROM DWH_PERFORMANCE.RTL_JOB_SS B);
COMMIT;

INSERT /*+ append */ INTO DWH_PERFORMANCE.RTL_ACTL_XCPTN_EMP_WK_SS
SELECT /*+ PARALLEL(a,6) */ * FROM  DWH_PERFORMANCE.RTL_ACTL_XCPTN_EMP_WK A 
WHERE FIN_YEAR_NO IN (2018,2019)
AND SK1_JOB_ID IN (SELECT  /*+ PARALLEL(b,6) */ SK1_JOB_ID FROM DWH_PERFORMANCE.RTL_JOB_SS B);
COMMIT;

INSERT /*+ append */ INTO DWH_PERFORMANCE.RTL_SCHED_XCPTN_EMP_DY_SS
SELECT /*+ PARALLEL(a,6) */ * FROM  DWH_PERFORMANCE.RTL_SCHED_XCPTN_EMP_DY A 
WHERE EXCEPTION_DATE >= '26/JUN/2017'
AND SK1_JOB_ID IN (SELECT  /*+ PARALLEL(b,6) */ SK1_JOB_ID FROM DWH_PERFORMANCE.RTL_JOB_SS B);
COMMIT;

INSERT /*+ append */ INTO DWH_PERFORMANCE.RTL_SCHED_XCPTN_EMP_WK_SS
SELECT /*+ PARALLEL(a,6) */ * FROM  DWH_PERFORMANCE.RTL_SCHED_XCPTN_EMP_WK A 
WHERE FIN_YEAR_NO IN (2018,2019)
AND SK1_JOB_ID IN (SELECT  /*+ PARALLEL(b,6) */ SK1_JOB_ID FROM DWH_PERFORMANCE.RTL_JOB_SS B);
COMMIT;
---------------------------------------------
--RUN FOUNDATION AND PEFORMANCE CLONED PROCS
---------------------------------------------

  -- FOUNDATION LAYER 

  DWH_FOUNDATION.WH_FND_S4S_014U_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_FOUNDATION.WH_FND_S4S_014A_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_FOUNDATION.WH_FND_S4S_014B_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_FOUNDATION.WH_FND_S4S_014C_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_FOUNDATION.WH_FND_S4S_014D_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_FOUNDATION.WH_FND_S4S_014E_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  
  -- HSP
  DWH_FOUNDATION.WH_FND_S4S_005U_SS_HSP(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);  

  -- PERFORMANCE LAYER

  DWH_PERFORMANCE.WH_PRF_S4S_014A_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_PERFORMANCE.WH_PRF_S4S_014B_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_PERFORMANCE.WH_PRF_S4S_014C_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_PERFORMANCE.WH_PRF_S4S_014D_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_PERFORMANCE.WH_PRF_S4S_014E_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);

  DWH_PERFORMANCE.WH_PRF_S4S_006U_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_PERFORMANCE.WH_PRF_S4S_021U_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_PERFORMANCE.WH_PRF_S4S_063U_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_PERFORMANCE.WH_PRF_S4S_065U_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_PERFORMANCE.WH_PRF_S4S_075U_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_PERFORMANCE.WH_PRF_S4S_073U_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_PERFORMANCE.WH_PRF_S4S_022U_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);

  DWH_PERFORMANCE.WH_PRF_S4S_050U_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_PERFORMANCE.WH_PRF_S4S_005U_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_PERFORMANCE.WH_PRF_S4S_009U_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_PERFORMANCE.WH_PRF_S4S_032U_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_PERFORMANCE.WH_PRF_S4S_051U_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);  
  DWH_PERFORMANCE.WH_PRF_S4S_044U_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);   

  DWH_PERFORMANCE.WH_PRF_S4S_004A_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_PERFORMANCE.WH_PRF_S4S_004U_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);
  DWH_PERFORMANCE.WH_PRF_S4S_008U_SS(P_FORALL_LIMIT => P_FORALL_LIMIT,P_SUCCESS => P_SUCCESS);

END RUN_S4S_CLONED_PROCS_A_SEED_SS;
